language: minimal

dist: bionic

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images-ci/dist-keygen"


jobs:
    include:
    - env: COMPILER=gcc-9
    - env: COMPILER=gcc-8
    - env: COMPILER=gcc-7
    - env: COMPILER=clang-9
    - env: COMPILER=clang-8
    - env: COMPILER=clang-7 BUILD_OPT="-no-san" # Workaround for #32
    - env: COMPILER=clang-6
    - env: COMPILER=clang-5
    - env: COMPILER=gcc-9 BUILD_OPT="-valgrind"
    - env: COMPILER=gcc-9 BUILD_OPT="-flawfinder"


before_install:
  - docker pull ${DOCKER_IMG}/${COMPILER}:latest

script:
  - docker run --cap-add SYS_PTRACE -v ${PWD}:/mnt -it ${DOCKER_IMG}/${COMPILER} /bin/bash -c "cd /mnt; script/ci_build.sh ${BUILD_OPT}"
