language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images-ci/dist-keygen"


matrix:
    include:
    - env: COMPILER=gcc-8
    - env: COMPILER=gcc-7
    - env: COMPILER=clang-7 BUILD_OPT="-no-san" # Workaround for #32
    - env: COMPILER=clang-6
    - env: COMPILER=clang-5
    - env: COMPILER=gcc-8 BUILD_OPT="-valgrind"


before_install:
  - docker pull ${DOCKER_IMG}/${COMPILER}:latest

script:
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}/${COMPILER} /bin/bash -c "cd /mnt; script/ci_build.sh ${BUILD_OPT}"
